catalog
catalogDescription
	^ 'A binding to libnotify for Pharo.

This project is a fork of the squeak version [1] modified to use the Pharo unified FFI API. It also has been updated to match the specification of libnotify 0.7.6 [2] (the original implementation for Squeak was not up-to-date with this specification).

Links:
[1]: http://www.squeaksource.com/libnotify.html
[2]: https://developer.gnome.org/libnotify/
Github: https://github.com/juliendelplanque/LibnotifyBinding'